/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminCanalesRouteImport } from './routes/admin.canales'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRecepcionRouteImport } from './routes/admin.recepcion'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as ApiSyncChannelsRouteImport } from './routes/api.sync-channels'
import { Route as CasitasIndexRouteImport } from './routes/casitas.index'
import { Route as CasitasIdRouteImport } from './routes/casitas.$id'
import { Route as ApiIcalCasitaIdRouteImport } from './routes/api.ical.$casitaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCanalesRoute = AdminCanalesRouteImport.update({
  id: '/canales',
  path: '/canales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecepcionRoute = AdminRecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSyncChannelsRoute = ApiSyncChannelsRouteImport.update({
  id: '/api/sync-channels',
  path: '/api/sync-channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CasitasIndexRoute = CasitasIndexRouteImport.update({
  id: '/casitas/',
  path: '/casitas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasitasIdRoute = CasitasIdRouteImport.update({
  id: '/casitas/$id',
  path: '/casitas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIcalCasitaIdRoute = ApiIcalCasitaIdRouteImport.update({
  id: '/api/ical/$casitaId',
  path: '/api/ical/$casitaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/canales': typeof AdminCanalesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recepcion': typeof AdminRecepcionRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/api/sync-channels': typeof ApiSyncChannelsRoute
  '/casitas/$id': typeof CasitasIdRoute
  '/admin/': typeof AdminIndexRoute
  '/casitas/': typeof CasitasIndexRoute
  '/api/ical/$casitaId': typeof ApiIcalCasitaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/canales': typeof AdminCanalesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recepcion': typeof AdminRecepcionRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/api/sync-channels': typeof ApiSyncChannelsRoute
  '/casitas/$id': typeof CasitasIdRoute
  '/admin': typeof AdminIndexRoute
  '/casitas': typeof CasitasIndexRoute
  '/api/ical/$casitaId': typeof ApiIcalCasitaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/canales': typeof AdminCanalesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recepcion': typeof AdminRecepcionRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/api/sync-channels': typeof ApiSyncChannelsRoute
  '/casitas/$id': typeof CasitasIdRoute
  '/admin/': typeof AdminIndexRoute
  '/casitas/': typeof CasitasIndexRoute
  '/api/ical/$casitaId': typeof ApiIcalCasitaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/calendario'
    | '/admin/canales'
    | '/admin/login'
    | '/admin/recepcion'
    | '/admin/reservas'
    | '/api/sync-channels'
    | '/casitas/$id'
    | '/admin/'
    | '/casitas/'
    | '/api/ical/$casitaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/calendario'
    | '/admin/canales'
    | '/admin/login'
    | '/admin/recepcion'
    | '/admin/reservas'
    | '/api/sync-channels'
    | '/casitas/$id'
    | '/admin'
    | '/casitas'
    | '/api/ical/$casitaId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/calendario'
    | '/admin/canales'
    | '/admin/login'
    | '/admin/recepcion'
    | '/admin/reservas'
    | '/api/sync-channels'
    | '/casitas/$id'
    | '/admin/'
    | '/casitas/'
    | '/api/ical/$casitaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiSyncChannelsRoute: typeof ApiSyncChannelsRoute
  CasitasIdRoute: typeof CasitasIdRoute
  CasitasIndexRoute: typeof CasitasIndexRoute
  ApiIcalCasitaIdRoute: typeof ApiIcalCasitaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/canales': {
      id: '/admin/canales'
      path: '/canales'
      fullPath: '/admin/canales'
      preLoaderRoute: typeof AdminCanalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recepcion': {
      id: '/admin/recepcion'
      path: '/recepcion'
      fullPath: '/admin/recepcion'
      preLoaderRoute: typeof AdminRecepcionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/sync-channels': {
      id: '/api/sync-channels'
      path: '/api/sync-channels'
      fullPath: '/api/sync-channels'
      preLoaderRoute: typeof ApiSyncChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casitas/': {
      id: '/casitas/'
      path: '/casitas'
      fullPath: '/casitas/'
      preLoaderRoute: typeof CasitasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casitas/$id': {
      id: '/casitas/$id'
      path: '/casitas/$id'
      fullPath: '/casitas/$id'
      preLoaderRoute: typeof CasitasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ical/$casitaId': {
      id: '/api/ical/$casitaId'
      path: '/api/ical/$casitaId'
      fullPath: '/api/ical/$casitaId'
      preLoaderRoute: typeof ApiIcalCasitaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminCanalesRoute: typeof AdminCanalesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRecepcionRoute: typeof AdminRecepcionRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminCanalesRoute: AdminCanalesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRecepcionRoute: AdminRecepcionRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiSyncChannelsRoute: ApiSyncChannelsRoute,
  CasitasIdRoute: CasitasIdRoute,
  CasitasIndexRoute: CasitasIndexRoute,
  ApiIcalCasitaIdRoute: ApiIcalCasitaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
